#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"
require "yaml"

root = Pathname(ENV.fetch("JEKYLL_SITE_ROOT", __dir__)).expand_path
posts_dir = root.join("_posts")
input = ARGV.join(" ").strip
abort 'Usage: ./newpost "Category Post title"' if input.empty?

category, title = input.split(/\s+/, 2)
abort 'Usage: ./newpost "Category Post title"' if title.nil? || title.strip.empty?

title = title.strip
slug = title.downcase.gsub(/[^[:alnum:]]+/, "-").gsub(/\A-|-\z/, "")
abort "Post title does not produce a filename" if slug.empty?

posts_dir.mkpath
category_pattern = Regexp.new("\\A\\d{4}-\\d{2}-\\d{2}-#{Regexp.escape(category.downcase)}-\\d+-")
sequence = posts_dir.children.count { |path| path.basename.to_s.downcase.match?(category_pattern) } + 1
display_title = category.casecmp("journal").zero? ? "[논문리뷰] #{title}" : "[#{category}] #{title}"
filename = "#{Time.now.strftime('%Y-%m-%d')}-#{category.downcase}-#{sequence}-#{slug}.md"
path = posts_dir.join(filename)

front_matter = {
  "layout" => "post",
  "title" => display_title,
  "section-type" => "post",
  "category" => category,
  "tags" => %w[tag1 tag2]
}

body = +YAML.dump(front_matter)
body << "---\n"
if category.casecmp("journal").zero?
  body << <<~MARKDOWN

    ## Author

    <p style="text-align: center;">Mark Zuckerberg, Bill Gates, Larry Page, Steve Wozniak, Elon Musk</p>

    <p style="text-align: center;">in <i>Some Laboratory or University</i></p>
    <br><br>
    Original Link: [Where did I find](https://web.stanford.edu/~ouster/cgi-bin/papers/ramcloud.pdf)<br>
    Archived Link: [Download in Google Drive](https://drive.google.com/file/d/14W9_7I734yKBpeVaPptRjw0lJ0DdhtXl/view?usp=sharing)

    ## 필자요약

    ## Introduction

    <br>
    <br>
    <br>
    <hr/>
  MARKDOWN
end

File.open(path, File::WRONLY | File::CREAT | File::EXCL) { |file| file.write(body) }
puts path.relative_path_from(root)
