#!/usr/bin/env ruby

unless ARGV[0]
  puts 'Usage: newpost "the post title"'
  exit(-1)
end

date_prefix = Time.now.strftime("%Y-%m-%d")
postname = ARGV[0].strip.downcase.gsub(/ /, '-')
post = "C:/jekyll/TyeolRik.github.io/_posts/#{date_prefix}-#{postname}.md"

header = <<-END
---
layout: post
title: "#{ARGV[0]}"
section-type: post
category: Category
tags: [ 'tag1', 'tag2' ]
---
END

File.open(post, 'w') do |f|
  f << header
end

system("atom", post)
